/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Scar API
 * OpenAPI spec version: 0.0.1
 */
import { http } from '../client/http';
export type HelloWorld200 = {
  message: string;
};

export type HelloWorld500 = {
  message: string;
};

export type UploadFile200 = {
  url: string;
  originalFileName: string;
};

export type UploadFile500 = {
  message: string;
};

export type LoginBody = {
  email: string;
  /**
   * @minLength 6
   * @maxLength 60
   */
  password: string;
};

export type Login200 = {
  id: number;
  /**
   * @minLength 3
   * @maxLength 60
   */
  name: string;
  email: string;
  token: string;
  refreshToken: string;
};

export type Login500 = {
  message: string;
};

export type RegisterUserBody = {
  /**
   * @minLength 3
   * @maxLength 60
   */
  name: string;
  email: string;
  /**
   * @minLength 6
   * @maxLength 60
   */
  password: string;
};

export type RegisterUser200 = {
  id: number;
  /**
   * @minLength 3
   * @maxLength 60
   */
  name: string;
  email: string;
  token: string;
  refreshToken: string;
};

export type RegisterUser500 = {
  message: string;
};

export type UpdateUserBody = {
  id?: number;
  /**
   * @minLength 3
   * @maxLength 60
   */
  name?: string;
  email?: string;
  password?: string;
};

export type UpdateUser200 = {
  id: number;
  /**
   * @minLength 3
   * @maxLength 60
   */
  name: string;
  email: string;
  createdAt: string;
};

export type UpdateUser500 = {
  message: string;
};

export type BboxCicatrizParams = {
bbox: number[];
startDate?: string;
endDate?: string;
limit?: number;
offset?: number;
};

export type BboxCicatriz201DataItemStatus = typeof BboxCicatriz201DataItemStatus[keyof typeof BboxCicatriz201DataItemStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const BboxCicatriz201DataItemStatus = {
  pending: 'pending',
  processing: 'processing',
  completed: 'completed',
  failed: 'failed',
} as const;

export type BboxCicatriz201DataItem = {
  id: string;
  jobId: string;
  /** @nullable */
  stacId: string | null;
  /** @nullable */
  uploadId: number | null;
  /** @nullable */
  createdAt: string | null;
  status: BboxCicatriz201DataItemStatus;
  /** @nullable */
  url: string | null;
  /** @nullable */
  collection: string | null;
  /** @nullable */
  startDate: string | null;
  /** @nullable */
  endDate: string | null;
  bbox: number[];
  geometry?: unknown;
};

export type BboxCicatriz201 = {
  data: BboxCicatriz201DataItem[];
  count: number;
};

export type BboxCicatriz400 = {
  message: string;
};

export type ScarCheck200Status = typeof ScarCheck200Status[keyof typeof ScarCheck200Status];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ScarCheck200Status = {
  pending: 'pending',
  processing: 'processing',
  completed: 'completed',
  failed: 'failed',
} as const;

export type ScarCheck200 = {
  status: ScarCheck200Status;
  jobId: string;
};

export type ScarCheck400 = {
  message: string;
};

export type StacSearchBody = {
  collections: string[];
  /**
   * @minItems 4
   * @maxItems 4
   */
  bbox: number[];
  datetime: string;
  limit?: number;
  ignore_existing?: boolean;
};

export type StacSearch200 = {
  jobId: string;
  status: string;
  message: string;
};

export type StacSearch400 = {
  message: string;
};

export type FinalizeCicatrizParams = {
jobId: string;
status: FinalizeCicatrizStatus;
};

export type FinalizeCicatrizStatus = typeof FinalizeCicatrizStatus[keyof typeof FinalizeCicatrizStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const FinalizeCicatrizStatus = {
  pending: 'pending',
  processing: 'processing',
  completed: 'completed',
  failed: 'failed',
} as const;

export type FinalizeCicatriz200 = {
  message: string;
};

export type FinalizeCicatriz500 = {
  message: string;
};

export type AllCicatrizParams = {
startDate?: string;
endDate?: string;
limit?: number;
offset?: number;
};

export type AllCicatriz201DataItemStatus = typeof AllCicatriz201DataItemStatus[keyof typeof AllCicatriz201DataItemStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AllCicatriz201DataItemStatus = {
  pending: 'pending',
  processing: 'processing',
  completed: 'completed',
  failed: 'failed',
} as const;

export type AllCicatriz201DataItem = {
  id: string;
  jobId: string;
  /** @nullable */
  stacId: string | null;
  /** @nullable */
  uploadId: number | null;
  /** @nullable */
  createdAt: string | null;
  status: AllCicatriz201DataItemStatus;
  /** @nullable */
  url: string | null;
};

export type AllCicatriz201 = {
  data: AllCicatriz201DataItem[];
  count: number;
};

export type AllCicatriz400 = {
  message: string;
};

export type SearchCicatrizById201Status = typeof SearchCicatrizById201Status[keyof typeof SearchCicatrizById201Status];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const SearchCicatrizById201Status = {
  pending: 'pending',
  processing: 'processing',
  completed: 'completed',
  failed: 'failed',
} as const;

export type SearchCicatrizById201 = {
  id: string;
  jobId: string;
  /** @nullable */
  stacId: string | null;
  /** @nullable */
  uploadId: number | null;
  /** @nullable */
  createdAt: string | null;
  status: SearchCicatrizById201Status;
  /** @nullable */
  url: string | null;
  /** @nullable */
  collection: string | null;
  /** @nullable */
  startDate: string | null;
  /** @nullable */
  endDate: string | null;
  bbox: number[];
  geometry?: unknown;
};

export type SearchCicatrizById400 = {
  message: string;
};

export type AnalyticsCicatriz200Status = typeof AnalyticsCicatriz200Status[keyof typeof AnalyticsCicatriz200Status];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AnalyticsCicatriz200Status = {
  pending: 'pending',
  processing: 'processing',
  completed: 'completed',
  failed: 'failed',
} as const;

export type AnalyticsCicatriz200GeometryType = typeof AnalyticsCicatriz200GeometryType[keyof typeof AnalyticsCicatriz200GeometryType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AnalyticsCicatriz200GeometryType = {
  Polygon: 'Polygon',
  MultiPolygon: 'MultiPolygon',
} as const;

export type AnalyticsCicatriz200Geometry = {
  type: AnalyticsCicatriz200GeometryType;
  ringCount: number;
  vertexCount: number;
};

export type AnalyticsCicatriz200 = {
  id: string;
  jobId: string;
  /** @nullable */
  stacId: string | null;
  /** @nullable */
  uploadId: number | null;
  /** @nullable */
  createdAt: string | null;
  status: AnalyticsCicatriz200Status;
  /** @nullable */
  url: string | null;
  /** @nullable */
  collection: string | null;
  /** @nullable */
  startDate: string | null;
  /** @nullable */
  endDate: string | null;
  bbox: number[];
  geometry: AnalyticsCicatriz200Geometry;
  area: string;
  perimeter: string;
  centroid: number[];
};

export type AnalyticsCicatriz400 = {
  message: string;
};

export type TestParams = {
jobId: string;
};

export type TestBodyNdviStatsHistogramItem = {
  /**
   * @minItems 2
   * @maxItems 2
   */
  range: number[];
  count: number;
};

export type TestBodyNdviStats = {
  min: number;
  max: number;
  mean: number;
  std: number;
  pct_acima_0_5: number;
  histogram: TestBodyNdviStatsHistogramItem[];
};

export type TestBodyAreaStatsPorClasse = {[key: string]: {
  pixels: number;
  area_m2: number;
  area_ha: number;
  area_km2: number;
}};

export type TestBodyAreaStatsSummary = {
  total_area_km2: number;
  burned_area_km2: number;
  burned_percent: number;
};

export type TestBodyAreaStats = {
  total_area_m2: number;
  total_area_ha: number;
  por_classe: TestBodyAreaStatsPorClasse;
  summary: TestBodyAreaStatsSummary;
};

export type TestBody = {
  bbox_real: number[];
  ndvi_stats: TestBodyNdviStats;
  area_stats: TestBodyAreaStats;
};

export type Test200 = {
  message: string;
};

export type Test400 = {
  message: string;
};

export type SaveAnalyticsParams = {
jobId: string;
};

export type SaveAnalyticsBodyNdviStatsHistogramItem = {
  /**
   * @minItems 2
   * @maxItems 2
   */
  range: number[];
  count: number;
};

export type SaveAnalyticsBodyNdviStats = {
  min: number;
  max: number;
  mean: number;
  std: number;
  pct_acima_0_5: number;
  histogram: SaveAnalyticsBodyNdviStatsHistogramItem[];
};

export type SaveAnalyticsBodyAreaStatsPorClasse = {[key: string]: {
  pixels: number;
  area_m2: number;
  area_ha: number;
  area_km2: number;
}};

export type SaveAnalyticsBodyAreaStatsSummary = {
  total_area_km2: number;
  burned_area_km2: number;
  burned_percent: number;
};

export type SaveAnalyticsBodyAreaStats = {
  total_area_m2: number;
  total_area_ha: number;
  por_classe: SaveAnalyticsBodyAreaStatsPorClasse;
  summary: SaveAnalyticsBodyAreaStatsSummary;
};

export type SaveAnalyticsBody = {
  bbox_real: number[];
  ndvi_stats: SaveAnalyticsBodyNdviStats;
  area_stats: SaveAnalyticsBodyAreaStats;
};

export type SaveAnalytics200 = {
  message: string;
};

export type SaveAnalytics400 = {
  message: string;
};

export type GetNvdiSummary200 = {
  min: number;
  max: number;
  mean: number;
  std: number;
  scarId: string;
  /** @nullable */
  analyticsId: number | null;
  nvdiId: number;
  pctAcima05: number;
};

export type GetNvdiSummary400 = {
  message: string;
};

export type GetNvdiStats200HistogramItem = {
  /**
   * @minItems 2
   * @maxItems 2
   */
  range: number[];
  count: number;
};

export type GetNvdiStats200 = {
  min: number;
  max: number;
  mean: number;
  std: number;
  pct_acima_0_5: number;
  histogram: GetNvdiStats200HistogramItem[];
  scarId: string;
  /** @nullable */
  analyticsId: number | null;
  nvdiId: number;
};

export type GetNvdiStats400 = {
  message: string;
};

export type GetAreaStats200ClassesItem = {
  pixels: number;
  area_m2: number;
  area_ha: number;
  area_km2: number;
  label: string;
  classe: string;
};

export type GetAreaStats200 = {
  scarId: string;
  /** @nullable */
  analyticsId: number | null;
  totalAreaM2: number;
  totalAreaHa: number;
  areaStatsId: number;
  classes: GetAreaStats200ClassesItem[];
};

export type GetAreaStats400 = {
  message: string;
};

export type GetAreaSummary200 = {
  scarId: string;
  /** @nullable */
  analyticsId: number | null;
  summaryId: number;
  totalAreaKm2: number;
  burnedAreaKm2: number;
  burnedPercent: number;
};

export type GetAreaSummary400 = {
  message: string;
};

export type GetAllDataAnalytics200AreaStats = {
  id: number;
  analyticsId: number;
  total_area_m2: number;
  total_area_ha: number;
  por_classe?: unknown;
};

export type GetAllDataAnalytics200NdviStats = {
  id: number;
  analyticsId: number;
  min: number;
  max: number;
  mean: number;
  std: number;
  pct_acima_0_5: number;
  histogram?: unknown;
};

export type GetAllDataAnalytics200AreaSummary = {
  id: number;
  analyticsId: number;
  total_area_km2: number;
  burned_area_km2: number;
  burned_percent: number;
};

export type GetAllDataAnalytics200 = {
  id: string;
  analyticsId: number;
  stacId: string;
  /** @nullable */
  uploadId: number | null;
  url: string;
  areaStats: GetAllDataAnalytics200AreaStats;
  ndviStats: GetAllDataAnalytics200NdviStats;
  areaSummary: GetAllDataAnalytics200AreaSummary;
};

export type GetAllDataAnalytics400 = {
  message: string;
};

export type GetGeometry200Type = typeof GetGeometry200Type[keyof typeof GetGeometry200Type];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetGeometry200Type = {
  Polygon: 'Polygon',
  MultiPolygon: 'MultiPolygon',
} as const;

export type GetGeometry200 = {
  areaKm2: number;
  perimeterKm: number;
  /**
   * @minItems 4
   * @maxItems 4
   */
  bbox: unknown[];
  /**
   * @minItems 2
   * @maxItems 2
   */
  centroid: unknown[];
  ringCount: number;
  type: GetGeometry200Type;
  vertexCount: number;
};

export type GetGeometry400 = {
  message: string;
};

export type GetAnalyticsParams = {
limit?: number;
offset?: number;
startDate?: string;
endDate?: string;
};

export type GetAnalytics200Item = {
  id: number;
  scarId: string;
  /**
   * @minItems 4
   * @maxItems 4
   */
  bboxReal: unknown[];
  /** @nullable */
  createdAt: string | null;
};

export type GetAnalytics400 = {
  message: string;
};

export type SearchLatLngParams = {
lat: number;
lng: number;
page?: number;
};

export type SearchLatLng200Item = {
  id: number;
  bbox_real: number[];
  /** @nullable */
  created_at: string | null;
};

export type SearchLatLng400 = {
  message: string;
};

export type GetHistogramAverageHistory200AveragesItemRange = {
  from: number;
  to: number;
};

export type GetHistogramAverageHistory200AveragesItem = {
  range: GetHistogramAverageHistory200AveragesItemRange;
  averageCount: number;
};

export type GetHistogramAverageHistory200 = {
  averages: GetHistogramAverageHistory200AveragesItem[];
};

export type GetHistogramAverageHistory400 = {
  message: string;
};

export type GetStatsOverview200 = {
  totalAreas: number;
  /** @nullable */
  totalAreaKm2: string | null;
  /** @nullable */
  totalBurnedKm2: string | null;
  /** @nullable */
  avgNdvi: string | null;
  /** @nullable */
  minDate: string | null;
  /** @nullable */
  maxDate: string | null;
};

export type GetStatsOverview400 = {
  message: string;
};

export type GetLastAnalytics200ItemAreaStats = {
  id: number;
  analyticsId: number;
  total_area_m2: number;
  total_area_ha: number;
  por_classe?: unknown;
};

export type GetLastAnalytics200ItemNdviStats = {
  id: number;
  analyticsId: number;
  min: number;
  max: number;
  mean: number;
  std: number;
  pct_acima_0_5: number;
  histogram?: unknown;
};

export type GetLastAnalytics200ItemAreaSummary = {
  id: number;
  analyticsId: number;
  total_area_km2: number;
  burned_area_km2: number;
  burned_percent: number;
};

export type GetLastAnalytics200Item = {
  id: string;
  analyticsId: number;
  stacId: string;
  /** @nullable */
  uploadId: number | null;
  areaStats: GetLastAnalytics200ItemAreaStats;
  ndviStats: GetLastAnalytics200ItemNdviStats;
  areaSummary: GetLastAnalytics200ItemAreaSummary;
};

export type GetLastAnalytics400 = {
  message: string;
};

/**
 * @summary Example route
 */
export const getHelloWorldUrl = () => {


  

  return `http://localhost:3030/api/hello-world`
}

export const helloWorld = async ( options?: RequestInit): Promise<HelloWorld200> => {
  
  return http<HelloWorld200>(getHelloWorldUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}



/**
 * @summary Upload de arquivo para S3
 */
export const getUploadFileUrl = () => {


  

  return `http://localhost:3030/upload`
}

export const uploadFile = async ( options?: RequestInit): Promise<UploadFile200> => {
  
  return http<UploadFile200>(getUploadFileUrl(),
  {      
    ...options,
    method: 'POST'
    
    
  }
);}



/**
 * @summary Login an user
 */
export const getLoginUrl = () => {


  

  return `http://localhost:3030/users/login`
}

export const login = async (loginBody: LoginBody, options?: RequestInit): Promise<Login200> => {
  
  return http<Login200>(getLoginUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      loginBody,)
  }
);}



/**
 * @summary Register an user
 */
export const getRegisterUserUrl = () => {


  

  return `http://localhost:3030/users/register`
}

export const registerUser = async (registerUserBody: RegisterUserBody, options?: RequestInit): Promise<RegisterUser200> => {
  
  return http<RegisterUser200>(getRegisterUserUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      registerUserBody,)
  }
);}



/**
 * @summary Update an user
 */
export const getUpdateUserUrl = () => {


  

  return `http://localhost:3030/users/edit`
}

export const updateUser = async (updateUserBody: UpdateUserBody, options?: RequestInit): Promise<UpdateUser200> => {
  
  return http<UpdateUser200>(getUpdateUserUrl(),
  {      
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      updateUserBody,)
  }
);}



/**
 * @summary Criar processamento de cicatriz
 */
export const getStacSearchUrl = () => {


  

  return `http://localhost:3030/cicatriz/create`
}

export const stacSearch = async (stacSearchBody: StacSearchBody, options?: RequestInit): Promise<StacSearch200> => {
  
  return http<StacSearch200>(getStacSearchUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      stacSearchBody,)
  }
);}



/**
 * @summary Pesquisar imagens de queimada por bbox
 */
export const getBboxCicatrizUrl = (params: BboxCicatrizParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `http://localhost:3030/cicatriz/bbox?${stringifiedParams}` : `http://localhost:3030/cicatriz/bbox`
}

export const bboxCicatriz = async (params: BboxCicatrizParams, options?: RequestInit): Promise<BboxCicatriz201> => {
  
  return http<BboxCicatriz201>(getBboxCicatrizUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}



/**
 * @summary Checa o status do processamento de uma cicatriz
 */
export const getScarCheckUrl = (jobId: string,) => {


  

  return `http://localhost:3030/cicatriz/check/${jobId}`
}

export const scarCheck = async (jobId: string, options?: RequestInit): Promise<ScarCheck200> => {
  
  return http<ScarCheck200>(getScarCheckUrl(jobId),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}



/**
 * @summary Finaliza o processamento de uma cicatriz
 */
export const getFinalizeCicatrizUrl = (params: FinalizeCicatrizParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `http://localhost:3030/cicatriz/finalize?${stringifiedParams}` : `http://localhost:3030/cicatriz/finalize`
}

export const finalizeCicatriz = async (params: FinalizeCicatrizParams, options?: RequestInit): Promise<FinalizeCicatriz200> => {
  
  return http<FinalizeCicatriz200>(getFinalizeCicatrizUrl(params),
  {      
    ...options,
    method: 'POST'
    
    
  }
);}



/**
 * @summary Pesquisar todas as imagens de cicatriz
 */
export const getAllCicatrizUrl = (params?: AllCicatrizParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `http://localhost:3030/cicatriz/all?${stringifiedParams}` : `http://localhost:3030/cicatriz/all`
}

export const allCicatriz = async (params?: AllCicatrizParams, options?: RequestInit): Promise<AllCicatriz201> => {
  
  return http<AllCicatriz201>(getAllCicatrizUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}



/**
 * @summary Pesquisar imagens de queimada por id
 */
export const getSearchCicatrizByIdUrl = (id: string,) => {


  

  return `http://localhost:3030/cicatriz/${id}`
}

export const searchCicatrizById = async (id: string, options?: RequestInit): Promise<SearchCicatrizById201> => {
  
  return http<SearchCicatrizById201>(getSearchCicatrizByIdUrl(id),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}



/**
 * @summary Gerar analytics de cicatriz por id
 */
export const getAnalyticsCicatrizUrl = (id: string,) => {


  

  return `http://localhost:3030/cicatriz/analytics/${id}`
}

export const analyticsCicatriz = async (id: string, options?: RequestInit): Promise<AnalyticsCicatriz200> => {
  
  return http<AnalyticsCicatriz200>(getAnalyticsCicatrizUrl(id),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}



/**
 * @summary Checa o status do processamento de uma cicatriz
 */
export const getTestUrl = (params: TestParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `http://localhost:3030/cicatriz/test?${stringifiedParams}` : `http://localhost:3030/cicatriz/test`
}

export const test = async (testBody: TestBody,
    params: TestParams, options?: RequestInit): Promise<Test200> => {
  
  return http<Test200>(getTestUrl(params),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      testBody,)
  }
);}



/**
 * Salva os dados de analytics de uma cicatriz
 * @summary Salva os dados de analytics de uma cicatriz
 */
export const getSaveAnalyticsUrl = (params: SaveAnalyticsParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `http://localhost:3030/analytics/save-analytics?${stringifiedParams}` : `http://localhost:3030/analytics/save-analytics`
}

export const saveAnalytics = async (saveAnalyticsBody: SaveAnalyticsBody,
    params: SaveAnalyticsParams, options?: RequestInit): Promise<SaveAnalytics200> => {
  
  return http<SaveAnalytics200>(getSaveAnalyticsUrl(params),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      saveAnalyticsBody,)
  }
);}



/**
 * @summary Busca os dados do status do nvdi de uma cicatriz
 */
export const getGetNvdiSummaryUrl = (scarId: string,) => {


  

  return `http://localhost:3030/analytics/${scarId}/nvdi-summary`
}

export const getNvdiSummary = async (scarId: string, options?: RequestInit): Promise<GetNvdiSummary200> => {
  
  return http<GetNvdiSummary200>(getGetNvdiSummaryUrl(scarId),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}



/**
 * @summary Busca os dados do status do nvdi completo de uma cicatriz
 */
export const getGetNvdiStatsUrl = (scarId: string,) => {


  

  return `http://localhost:3030/analytics/${scarId}/nvdi-stats`
}

export const getNvdiStats = async (scarId: string, options?: RequestInit): Promise<GetNvdiStats200> => {
  
  return http<GetNvdiStats200>(getGetNvdiStatsUrl(scarId),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}



/**
 * @summary Busca os dados do status da área de uma cicatriz
 */
export const getGetAreaStatsUrl = (scarId: string,) => {


  

  return `http://localhost:3030/analytics/${scarId}/area-stats`
}

export const getAreaStats = async (scarId: string, options?: RequestInit): Promise<GetAreaStats200> => {
  
  return http<GetAreaStats200>(getGetAreaStatsUrl(scarId),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}



/**
 * @summary Busca os dados do resumo do status da area de uma cicatriz
 */
export const getGetAreaSummaryUrl = (scarId: string,) => {


  

  return `http://localhost:3030/analytics/${scarId}/area-summary`
}

export const getAreaSummary = async (scarId: string, options?: RequestInit): Promise<GetAreaSummary200> => {
  
  return http<GetAreaSummary200>(getGetAreaSummaryUrl(scarId),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}



/**
 * @summary Busca os dados completos de uma cicatriz
 */
export const getGetAllDataAnalyticsUrl = (scarId: string,) => {


  

  return `http://localhost:3030/analytics/${scarId}/all`
}

export const getAllDataAnalytics = async (scarId: string, options?: RequestInit): Promise<GetAllDataAnalytics200> => {
  
  return http<GetAllDataAnalytics200>(getGetAllDataAnalyticsUrl(scarId),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}



/**
 * @summary Gera a geometria de uma cicatriz
 */
export const getGetGeometryUrl = (scarId: string,) => {


  

  return `http://localhost:3030/analytics/${scarId}/geometry`
}

export const getGeometry = async (scarId: string, options?: RequestInit): Promise<GetGeometry200> => {
  
  return http<GetGeometry200>(getGetGeometryUrl(scarId),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}



/**
 * @summary Busca por todas as estatísticas
 */
export const getGetAnalyticsUrl = (params?: GetAnalyticsParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `http://localhost:3030/analytics?${stringifiedParams}` : `http://localhost:3030/analytics`
}

export const getAnalytics = async (params?: GetAnalyticsParams, options?: RequestInit): Promise<GetAnalytics200Item[]> => {
  
  return http<GetAnalytics200Item[]>(getGetAnalyticsUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}



/**
 * @summary Busca por cicatrizes em uma área geográfica
 */
export const getSearchLatLngUrl = (params: SearchLatLngParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `http://localhost:3030/analytics/search-lat-lng?${stringifiedParams}` : `http://localhost:3030/analytics/search-lat-lng`
}

export const searchLatLng = async (params: SearchLatLngParams, options?: RequestInit): Promise<SearchLatLng200Item[]> => {
  
  return http<SearchLatLng200Item[]>(getSearchLatLngUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}



/**
 * @summary Busca os dados do histograma médio de uma cicatriz
 */
export const getGetHistogramAverageHistoryUrl = () => {


  

  return `http://localhost:3030/analytics/histogram-average`
}

export const getHistogramAverageHistory = async ( options?: RequestInit): Promise<GetHistogramAverageHistory200> => {
  
  return http<GetHistogramAverageHistory200>(getGetHistogramAverageHistoryUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}



/**
 * @summary Busca a média dos dados de analytics salvos
 */
export const getGetStatsOverviewUrl = () => {


  

  return `http://localhost:3030/analytics/overview`
}

export const getStatsOverview = async ( options?: RequestInit): Promise<GetStatsOverview200> => {
  
  return http<GetStatsOverview200>(getGetStatsOverviewUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}



/**
 * @summary Busca os dados das últimas 5 analytics
 */
export const getGetLastAnalyticsUrl = () => {


  

  return `http://localhost:3030/analytics/last`
}

export const getLastAnalytics = async ( options?: RequestInit): Promise<GetLastAnalytics200Item[]> => {
  
  return http<GetLastAnalytics200Item[]>(getGetLastAnalyticsUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}
